# Generated by Django 5.1.6 on 2025-03-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_item_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="currency",
            field=models.CharField(
                choices=[("USD", "Доллар"), ("RUB", "Рубль")],
                default="USD",
                max_length=10,
                verbose_name="Валюта",
            ),
        ),
    ]
