# Generated by Django 5.1.6 on 2025-02-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_item_currency_alter_item_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(default="", verbose_name="Описание товара"),
        ),
    ]
